{{- if .Values.kyma.apiv1.enabled -}}
{{- $name := include "chart.name" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  {{- include "default_metadata" . | indent 2 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  authentication: []
  hostname: {{ $name }}
  service:
    name: {{ $name }}
    port: {{ $svcPort }}
{{- end }}
